apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity-sample
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: [simanau-gke@gcp-lab-1-vsimanau-319621.iam.gserviceaccount.com]
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:lab-1-vsimanau-319621.svc.id.goog[default/simanau-gke]
